name: Build and Deploy React App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: echo "${{ secrets.REACT_ENV_FILE }}" > .env

      - name: Build React App
        run: npm run build

      - name: Deploy to VPS via SCP
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "$KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              -r dist/* $USER@$HOST:/var/www/html/cpusimulator
